import Head from "next/head";
import { useRouter } from "next/router";
import prisma from "../../../lib/prisma";
import Layout from "../../../components/Layout";
import { useState } from "react";

export default function Draft({ feed }) {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const publishPost = async (postId) => {
    try {
      setLoading(true);
      const body = {
        published: true,
      };
      await fetch("/api/post/edit?id=" + postId, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });

      setLoading(false);
      await router.push("/");
    } catch (error) {
      console.log("error", error);
      setLoading(false);
    }
  };

  return (
    <Layout>
      <Head>
        <title>Drafts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {feed.length > 0 ? (
        feed.map((item, index) => (
          <div className="border p-4 mb-4 rounded-md post-card" key={index}>
            <a
              href={`posts/${item.id}`}
              className="text-blue-500 font-semibold"
            >
              {item.title}
            </a>
            <p className="mt-2">{item.content}</p>
            <div className="flex items-center justify-between mt-4">
              <button
                onClick={() => publishPost(item.id)}
                className="px-4 py-2 text-white bg-blue-500 rounded-md hover:bg-blue-600 focus:outline-none"
              >
                {loading ? "Loading..." : "Publish"}
              </button>
            </div>
          </div>
        ))
      ) : (
        <div>
          <p>No posts found.</p>
        </div>
      )}
    </Layout>
  );
}

export const getStaticProps = async () => {
  const feed = await prisma.post.findMany({
    where: { published: false },
    include: {
      comments: {
        select: { content: true },
      },
    },
  });
  return {
    props: { feed },
    revalidate: 10,
  };
};
